# Generated by Django 4.2.6 on 2024-02-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0003_alter_assessment_09a02_assessment_base_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment_09a02",
            name="assessment_base",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_09A02",
                to="upload.assessment_base",
            ),
        ),
        migrations.AlterField(
            model_name="assessment_09a0304",
            name="assessment_base",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_09A0304",
                to="upload.assessment_base",
            ),
        ),
        migrations.AlterField(
            model_name="assessment_10a01",
            name="assessment_base",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_10A01",
                to="upload.assessment_base",
            ),
        ),
        migrations.AlterField(
            model_name="assessment_10a02",
            name="assessment_base",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_10A02",
                to="upload.assessment_base",
            ),
        ),
    ]
