# Generated by Django 4.2.6 on 2024-02-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0008_alter_assessment_base_assessment_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment_09a0304", name="assessment_base",
        ),
        migrations.RemoveField(model_name="assessment_10a01", name="assessment_base",),
        migrations.RemoveField(model_name="assessment_10a02", name="assessment_base",),
        migrations.AlterModelOptions(
            name="assessment_base",
            options={
                "ordering": ["id"],
                "verbose_name": "考核信息",
                "verbose_name_plural": "考核信息",
            },
        ),
        migrations.AddField(
            model_name="assessment_base",
            name="additional_data",
            field=models.JSONField(blank=True, null=True, verbose_name="动态数据"),
        ),
        migrations.DeleteModel(name="Assessment_09A02",),
        migrations.DeleteModel(name="Assessment_09A0304",),
        migrations.DeleteModel(name="Assessment_10A01",),
        migrations.DeleteModel(name="Assessment_10A02",),
    ]
