# Generated by Django 4.2.6 on 2024-02-27 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0009_remove_assessment_09a0304_assessment_base_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment_Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                (
                    "assessment_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="upload.assessment_base",
                    ),
                ),
            ],
        ),
    ]
