# Generated by Django 4.2.6 on 2024-02-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0010_assessment_classification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment_classification",
            options={"verbose_name": "分类信息", "verbose_name_plural": "分类信息"},
        ),
        migrations.AddField(
            model_name="assessment_classification",
            name="data_key",
            field=models.CharField(
                default="default_key", max_length=255, verbose_name="数据键"
            ),
        ),
    ]
