# Generated by Django 4.2.6 on 2024-02-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0011_alter_assessment_classification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment_classification",
            name="category",
            field=models.CharField(max_length=50, verbose_name="分类"),
        ),
        migrations.AlterUniqueTogether(
            name="assessment_classification",
            unique_together={("assessment_base", "data_key")},
        ),
    ]
