# Generated by Django 4.2.6 on 2024-02-27 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0012_alter_assessment_classification_category_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assessment_classification", unique_together=set(),
        ),
    ]
